baseURL = "https://lab.ggszk.org/"
languageCode = 'ja-JP'
title = 'ggszk-lab'
theme = "PaperMod"

[params]
disableSpecial1stPost = true

[params.label]
  text = "ggszk-lab"
  icon = "images/ggszk-lab-logo_sq2.png"
  iconHeight = 35

[params.assets]
  favicon = "images/ggszk-lab-logo_sq2.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "お知らせ"
    url = "/posts/"
    weight = 5

  [[menu.main]]
    name = "プロフィール"
    url = "/profile/"
    weight = 10

  [[menu.main]]
    name = "研究活動"
    url = "/research/"
    weight = 20

  [[menu.main]]
    name = "研究成果"
    url = "/papers/"
    weight = 30

  [[menu.main]]
    name = "ゼミテーマ"
    url = "/students/"
    weight = 40

  [[menu.main]]
    name = "対外活動"
    url = "/activities/"
    weight = 45

  [[menu.main]]
    name = "音楽"
    url = "/music/"
    weight = 50

